### ISSUE TITLE
Clear up API

### ISSUE THREAD

**Issue by dy** [kobezzza/Escaper#1]
Hi @kobezzza!

Thanks for the good package, really valuable piece.
I was planning to use it in [prepr](https://ghub.io/prepr) and [scope-css](https://ghub.io/scope-css).

May I ask you to elaborate API in readme a bit, right now function signature seems confusing. Expected signature is:
`escape(string, how?, output)`
so that `how` specifies an options object with settings how to escape exactly, and `output` array collects the results. Right now `-1`, `true`, `false`, `object` as the second argument seem really confusing, as well as misleading options (`{@all: true, @comments: false}`). I would suggest simplifying it to

```js
// escape everything
escape(str, out)

// escape everything but comments
escape(str, {comments: false}, out)

// escape only custom comments
escape(str, {comments: ['/*', '//'], strings: false}, out)

// escape only C++ strings
escape(str, {strings: ["'", '"'], comments: false}, out)

// escape only passed signatures
escape(str, ['"', '/*', '/'], out)
```

Cheers!

**Comment by kobezzza** [comment]
Hi! Good proposal 👍 I'll take it to work in the next 2 weeks, or I'll be glad to accept PR

**Comment by kobezzza** [comment]
Done.
