### ISSUE TITLE
Module file not published on npm

### ISSUE THREAD

**Issue by selevt** [kobezzza/Escaper#10]
Hi @kobezzza 

In the package.json the `module` is referring to the `src/escaper.js` file, but this file is not published on NPM.

When importing packages in the Svelte REPL, it tries to load the module from unpkg, which currently fails for this package. As an example, see: https://svelte.dev/repl/4fd66c75394c40be9103c3de82f7b9c6?version=3.22.3

**Comment by kobezzza** [comment]
Hi! Sorry for the long response, I have fixed it in 3.0.5.
